image: alpine/edge
secrets:
  - stargate_ssh
tasks:
  - deploy: |
      ssh -o StrictHostKeyChecking=no krisyotam@stargate.taild7f15a.ts.net '
        set -eu
        cd ~/anki
        git fetch --quiet origin
        git reset --hard origin/main
        echo "anki deployed"
      '
